<a href="https://colab.research.google.com/github/Nazneen-akram/NED-Data-Science-Artificial-Intelligence/blob/main/Array_flattening.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### An **array** is a data structure that stores values of the same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to the same data type.

### Now, let’s understand what it means by flattening an array. Flattening an array means converting a multidimensional array into a 1D array.

In [1]:
import numpy as np

# Create a 2D array
array_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(array_2D)

# Flatten the 2D array
array_flattened = array_2D.flatten()
print("\nFlattened Array:")
print(array_flattened)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened Array:
[1 2 3 4 5 6 7 8 9]




1.   ## <font color='green'>Create a 3D array of shape (3,3,3) and flatten it.</font>



In [2]:
# Create a 3D array of shape (3,3,3)
array_3D = np.arange(27).reshape(3, 3, 3)
print("3D Array:")
print(array_3D)

# Flatten the 3D array
array_flattened = array_3D.flatten()
print("\nFlattened Array:")
print(array_flattened)

3D Array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Flattened Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]




2.   ### <font color ='green'>Write a Python program to create an array of 5 integers and display the array items. Access individual element through indexes.



In [5]:
#create an array of 5 integers
array_int = np.arange(6)
print(array_int)

#Access individual element through indexes
for i in array_int:
  print(array_int[i])

[0 1 2 3 4 5]
0
1
2
3
4
5




3. ###  <font color='green'>Write a Python program to append values to the end of an array.

In [9]:
#list of values
values = [6,7,8]
array_int = np.append(array_int,values,axis=0)
print(array_int)

[0 1 2 3 4 5 6 7 8]




4.  ### <font color='green'> Write a Python program to reverse an array (first element becomes last)

In [13]:
-np.sort(-array_int)

array([8, 7, 6, 5, 4, 3, 2, 1, 0])